# Generated by Django 3.0.6 on 2020-05-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0002_auto_20200510_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='artists.Artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='tracks.Track')),
            ],
        ),
    ]
