# Generated by Django 3.0.6 on 2020-05-10 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_trackfeatures'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackfeatures',
            table='track_features',
        ),
    ]
