# Generated by Django 3.0.4 on 2020-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_owner_profile'),
        ('tracks', '0004_auto_20200510_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(to='playlists.Playlist'),
        ),
    ]
