# Generated by Django 3.0.6 on 2020-05-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_auto_20200518_0116'),
        ('tracks', '0005_track_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='playlists',
            field=models.ManyToManyField(blank=True, to='playlists.Playlist'),
        ),
    ]
