# Generated by Django 3.0.6 on 2020-05-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_auto_20200518_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='playlists',
        ),
    ]
