# Generated by Django 3.0.6 on 2020-05-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_remove_track_playlists'),
        ('playlists', '0004_auto_20200518_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='tracks.Track'),
        ),
    ]
