# Generated by Django 3.0.6 on 2020-05-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_playlist_tracks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
    ]
