# Generated by Django 3.0.6 on 2020-05-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistfavorite',
            options={},
        ),
        migrations.AlterModelTable(
            name='artistfavorite',
            table='favorite_artists',
        ),
    ]
