# Generated by Django 3.0.6 on 2020-05-10 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20200510_0428'),
        ('albums', '0004_auto_20200510_0405'),
        ('favorites', '0002_auto_20200510_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackFavorite',
            fields=[
                ('favorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='favorites.Favorite')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracks.Track')),
            ],
            options={
                'db_table': 'favorite_tracks',
            },
            bases=('favorites.favorite',),
        ),
        migrations.CreateModel(
            name='AlbumFavorite',
            fields=[
                ('favorite_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='favorites.Favorite')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='albums.Album')),
            ],
            options={
                'db_table': 'favorite_albums',
            },
            bases=('favorites.favorite',),
        ),
    ]
