# Generated by Django 3.0.6 on 2020-05-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.FloatField(default=9.99),
        ),
    ]
